baseURL = "https://www.abetterinternet.org/"
languageCode = "en-us"

contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false

[params]
images = ["images/opengraph/ISRG-opengraph-wide.png"]
twitter_card_format = "summary"
social_share_twitter_square = "images/opengraph/ISRG-opengraph-square.png"
social_share_twitter_wide = "images/opengraph/ISRG-opengraph-wide.png"
math = true

# Date and time formatting, see https://gohugo.io/functions/format/
time_format_RFC3339 = "2006-01-02T15:04:05Z07:00"
time_format_RFC822 = "Mon, 02 Jan 2006 15:04:05 -0700"
time_format_default = "January, 2006"
time_format_chinese = "2006 年 1 月"

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark]
[markup.goldmark.extensions]
typographer = false
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)'], ['$', '$']]
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser]
# To keep § ids identical after the migration from blackfriday to goldmark
autoHeadingIDType = "blackfriday"



[languages]
[languages.en]
contentDir = "content/en"
title = "InspiringGroup"
languageName ="English"
# Weight used for sorting.
weight = 1
description = """
  Todo update this in config.toml
"""
[languages.zh-cn]
contentDir = "content/zh-cn"
title = "InspiringGroup"
languageName ="中文"
# Weight used for sorting.
weight = 2
description = """
  Todo update this in config.toml
"""
